---
title: Lighthouse Leadership
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
locale: en
title_separator: "-"
name: Your Name
description: An amazing website.
url: 
baseurl: 
repository: 
teaser: 
words_per_minute: 200
author:
  name: Your Name
  avatar: bio-photo.jpg
  bio: I am an amazing person.
  location: Somewhere
  email: 
  uri: 
  bitbucket: 
  codepen: 
  dribbble: 
  flickr: 
  facebook: 
  foursquare: 
  github: 
  google_plus: 
  keybase: 
  instagram: 
  lastfm: 
  linkedin: 
  pinterest: 
  soundcloud: 
  stackoverflow: 
  steam: 
  tumblr: 
  twitter: 
  vine: 
  weibo: 
  xing: 
  youtube: 
