---
title: Lighthouse Leadership
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
locale: en
title_separator: "-"
name: Your Name
description: An amazing website.
url:
baseurl:
repository:
teaser:
words_per_minute: 200

author:
  name: Your Name
  avatar: bio-photo.jpg
  bio: I am an amazing person.
  location: Somewhere
  email:
  uri:
  bitbucket:
  codepen:
  dribbble:
  flickr:
  facebook:
  foursquare:
  github:
  google_plus:
  keybase:
  instagram:
  lastfm:
  linkedin:
  pinterest:
  soundcloud:
  stackoverflow:
  steam:
  tumblr:
  twitter:
  vine:
  weibo:
  xing:
  youtube:

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
